### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by cathaypacific8747** [cathaypacific8747/am4bot#1]
Features implemented:
- [x] 

Features missing:
- [ ] user signup
- [ ] user login
- [ ] alliance api

**Comment by cathaypacific8747** [comment]
v0.2 feature tracking:
- [x] airport search and suggest
- [x] aircraft search and suggest
- [ ] route creation (ap > ap)
- [ ] aircraft-route creation (ap > ap, ac)
- [ ] route research (ap > *, ac)
